name: uts_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  get: 4.6.5
  google_sign_in: ^6.0.2
  intl: ^0.17.0
  table_calendar: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - image/
